# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c39THSoFXDqGc4mO7NZmd0fCt6JqI31e
"""

import pandas as pd
import numpy as np
df=pd.read_csv('car_dataset.data')
df

df.info()

df.replace('?',np.nan,inplace=True)
df.info()

headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
df.columns=headers
df.info()

df.info()

from sklearn.impute import SimpleImputer
imputer_mean=SimpleImputer(missing_values=np.nan,strategy='mean')
df['normalized-losses']=imputer_mean.fit_transform(df[['normalized-losses']]).astype(int)

"""df"""

df.info()

df.dropna(subset=['horsepower','peak-rpm','bore','stroke','num-of-doors'],axis=0,inplace=True)

df.info()
df

df.reset_index(drop=True,inplace=True)
df

df=pd.read_csv('Salary_Dataset.csv')
df

df.info()
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
encoded = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
dataset=pd.DataFrame(encoded.fit_transform(df))

dataset

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Purchased']=le.fit_transform(df['Purchased'])
df

